name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

 

      - name: Configura usuário git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Puxa as últimas mudanças do main
        run: git pull --rebase origin main

      - name: Adiciona e commita arquivos gerados
        run: |
          git add .
          git commit -m "Atualiza snake" || echo "Nada para commitar"

      - name: Faz push das alterações
        run: git push origin main
