name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Roda diariamente à meia-noite
  workflow_dispatch:  # Permite rodar manualmente também

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar o Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: 404xploit
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit e push do resultado
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "gerando snake.svg"
          add: "dist/github-contribution-grid-snake.svg"
