name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza todo dia à meia-noite UTC
  workflow_dispatch: # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ExploitEngineer
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
